baseURL = "/"
languageCode = "en"
DefaultContentLanguage = "en"
# title = "Website of Pavan Kemparaju"
theme = "anatole"
summarylength = 0
enableEmoji = true
enableRobotsTXT = true


# Top menu
[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/blog/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Posts by Categories"
  weight = 300
  identifier = "categories"
  url = "/categories/"

  [[menu.main]]
  name = "Posts by Tags"
  weight = 300
  identifier = "tags"
  url = "/tags/"

[params]
title = "Pavan Kemparaju"
author = "Pavan Kemparaju"
description = """Call me Pavan
this is my site
"""
profilePicture = "img/profile.jpg"
mainSections = ["post"]
contentRatio = 0.75

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true